In [2]:
import numpy as np

In [4]:
matrix = [[ 27.13,   7.77,  34.39],
       [ 27.99,   7.76,  34.93],
       [ 27.16,   6.96,  33.79],
       [ 27.17,   8.58,  33.79],
       [ 25.94,   7.78,  35.25],
       [ 25.98,   9.09,  36.02],
       [ 26.74,  10.1 ,  35.32],
       [ 26.75,  10.94,  35.86],
       [ 24.64,   7.79,  34.46],
       [ 24.53,   8.51,  33.5 ],
       [ 23.59,   7.07,  34.76],
       [ 23.59,   6.55,  35.61],
       [ 22.42,   7.01,  33.9 ],
       [ 21.62,   5.76,  34.27],
       [ 22.48,   4.21,  33.97],
       [ 21.59,   8.22,  34.04],
       [ 21.37,   8.69,  35.16]]

npMatrix = np.array(matrix)

np.mean(npMatrix, axis=0)

array([24.74647059,  7.81117647, 34.64823529])

In [ ]:

# [[1.         0.93776994 0.91118412 0.94409807 0.9789501  0.95236144 0.90100585 0.97895438 0.92470962 0.84664513 0.92799799 0.8686879 ]
#  [0.93776994 1.         0.83025078 0.89433892 0.95054287 0.88818878 0.85319939 0.95055283 0.94262821 0.75730169 0.9098895  0.88597805]
#  [0.91118412 0.83025078 1.         0.86409273 0.89657653 0.8619429 0.79235355 0.89656678 0.83269857 0.87788765 0.86559526 0.7537065 ]
#  [0.94409807 0.89433892 0.86409273 1.         0.92992271 0.99189631 0.92055368 0.92991804 0.87212334 0.85279855 0.89311909 0.90167932]
#  [0.9789501  0.95054287 0.89657653 0.92992271 1.         0.93828128 0.88864252 0.99999975 0.90382252 0.81495961 0.96428364 0.83123877]
#  [0.95236144 0.88818878 0.8619429  0.99189631 0.93828128 1. 0.929188   0.93827837 0.86292336 0.8530458  0.89974583 0.88685879]
#  [0.90100585 0.85319939 0.79235355 0.92055368 0.88864252 0.929188 1.         0.88863429 0.81740616 0.77501365 0.84612366 0.83113149]
#  [0.97895438 0.95055283 0.89656678 0.92991804 0.99999975 0.93827837 0.88863429 1.         0.90386388 0.81495849 0.96428439 0.83128508]
#  [0.92470962 0.94262821 0.83269857 0.87212334 0.90382252 0.86292336 0.81740616 0.90386388 1.         0.7799634  0.86837854 0.93902705]
#  [0.84664513 0.75730169 0.87788765 0.85279855 0.81495961 0.8530458 0.77501365 0.81495849 0.7799634  1.         0.78565492 0.75864332]
#  [0.92799799 0.9098895  0.86559526 0.89311909 0.96428364 0.89974583 0.84612366 0.96428439 0.86837854 0.78565492 1.         0.7916072 ]
#  [0.8686879  0.88597805 0.7537065  0.90167932 0.83123877 0.88685879 0.83113149 0.83128508 0.93902705 0.75864332 0.7916072  1.        ]]

In [7]:
mat = [[1, 2], [3, 4], [5, 6], [7, 8]]

npMat = np.array(mat)

npMat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
npMat.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])