In [1]:
import numpy as np

In [2]:
matrix = [[ 27.13,   7.77,  34.39],
       [ 27.99,   7.76,  34.93],
       [ 27.16,   6.96,  33.79],
       [ 27.17,   8.58,  33.79],
       [ 25.94,   7.78,  35.25],
       [ 25.98,   9.09,  36.02],
       [ 26.74,  10.1 ,  35.32],
       [ 26.75,  10.94,  35.86],
       [ 24.64,   7.79,  34.46],
       [ 24.53,   8.51,  33.5 ],
       [ 23.59,   7.07,  34.76],
       [ 23.59,   6.55,  35.61],
       [ 22.42,   7.01,  33.9 ],
       [ 21.62,   5.76,  34.27],
       [ 22.48,   4.21,  33.97],
       [ 21.59,   8.22,  34.04],
       [ 21.37,   8.69,  35.16]]

npMatrix = np.array(matrix)

np.mean(npMatrix, axis=0)

array([24.74647059,  7.81117647, 34.64823529])

In [3]:

# [[1.         0.93776994 0.91118412 0.94409807 0.9789501  0.95236144 0.90100585 0.97895438 0.92470962 0.84664513 0.92799799 0.8686879 ]
#  [0.93776994 1.         0.83025078 0.89433892 0.95054287 0.88818878 0.85319939 0.95055283 0.94262821 0.75730169 0.9098895  0.88597805]
#  [0.91118412 0.83025078 1.         0.86409273 0.89657653 0.8619429 0.79235355 0.89656678 0.83269857 0.87788765 0.86559526 0.7537065 ]
#  [0.94409807 0.89433892 0.86409273 1.         0.92992271 0.99189631 0.92055368 0.92991804 0.87212334 0.85279855 0.89311909 0.90167932]
#  [0.9789501  0.95054287 0.89657653 0.92992271 1.         0.93828128 0.88864252 0.99999975 0.90382252 0.81495961 0.96428364 0.83123877]
#  [0.95236144 0.88818878 0.8619429  0.99189631 0.93828128 1. 0.929188   0.93827837 0.86292336 0.8530458  0.89974583 0.88685879]
#  [0.90100585 0.85319939 0.79235355 0.92055368 0.88864252 0.929188 1.         0.88863429 0.81740616 0.77501365 0.84612366 0.83113149]
#  [0.97895438 0.95055283 0.89656678 0.92991804 0.99999975 0.93827837 0.88863429 1.         0.90386388 0.81495849 0.96428439 0.83128508]
#  [0.92470962 0.94262821 0.83269857 0.87212334 0.90382252 0.86292336 0.81740616 0.90386388 1.         0.7799634  0.86837854 0.93902705]
#  [0.84664513 0.75730169 0.87788765 0.85279855 0.81495961 0.8530458 0.77501365 0.81495849 0.7799634  1.         0.78565492 0.75864332]
#  [0.92799799 0.9098895  0.86559526 0.89311909 0.96428364 0.89974583 0.84612366 0.96428439 0.86837854 0.78565492 1.         0.7916072 ]
#  [0.8686879  0.88597805 0.7537065  0.90167932 0.83123877 0.88685879 0.83113149 0.83128508 0.93902705 0.75864332 0.7916072  1.        ]]

In [4]:
mat = [[1, 2], [3, 4], [5, 6], [7, 8]]

npMat = np.array(mat)

npMat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
npMat.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [6]:
A = [1,2,3]
B = [4,5,6]

a = np.asarray(A)
b = np.asarray(B)

rest = b @ a

In [7]:
rest

32

In [8]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import make_multilabel_classification
# This produces a feature matrix of token counts, similar to what
# CountVectorizer would produce on text.
X, _ = make_multilabel_classification(random_state=0)

print(len(X))
print(len(X[0]))




100
20


In [9]:
lda = LatentDirichletAllocation(n_components=5, random_state=0)
lda.fit(X)
# get topics for some given samples:
lda.transform(X)

# X[-2:]
# array([[0.00360392, 0.25499205, 0.0036211 , 0.64236448, 0.09541846],
#        [0.15297572, 0.00362644, 0.44412786, 0.39568399, 0.003586  ]])

array([[0.83264691, 0.15610504, 0.00372766, 0.00372946, 0.00379093],
       [0.11204968, 0.00563061, 0.00567138, 0.57851629, 0.29813204],
       [0.00361638, 0.15391126, 0.31659894, 0.52227005, 0.00360337],
       [0.50945646, 0.00426268, 0.00428521, 0.47775048, 0.00424517],
       [0.16992137, 0.18277504, 0.00356346, 0.61250018, 0.03123994],
       [0.00540098, 0.02177687, 0.30792814, 0.65946917, 0.00542484],
       [0.30475725, 0.00374199, 0.68408225, 0.00371419, 0.00370431],
       [0.00447199, 0.28837587, 0.00448506, 0.698175  , 0.00449208],
       [0.00437916, 0.00440988, 0.00438779, 0.9824583 , 0.00436487],
       [0.80996112, 0.17491121, 0.00503076, 0.00504055, 0.00505636],
       [0.00421521, 0.25666246, 0.28372318, 0.00422468, 0.45117447],
       [0.58527096, 0.00409741, 0.00411491, 0.21831721, 0.18819951],
       [0.52516563, 0.00360488, 0.4639673 , 0.0036168 , 0.00364539],
       [0.00375324, 0.20515083, 0.17315141, 0.6141886 , 0.00375592],
       [0.0052288 , 0.00522335, 0.

In [10]:
np.arange(2**8 + 1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
import numpy as np 

a = np.array([[0,0,5,2],[4,3,2,2],[0,5,1,3],[5,3,2,0]]) 
hist,bins = np.histogram(a,bins = [0,1,2,3,4,5,6]) 

print(a)
print(hist) 
print(bins)

[[0 0 5 2]
 [4 3 2 2]
 [0 5 1 3]
 [5 3 2 0]]
[4 1 4 3 1 3]
[0 1 2 3 4 5 6]


In [2]:
import numpy as np

A = [45,37,42,35,39]
B = [38,31,26,28,33]
C = [10,15,17,21,12]

data = np.array([A,B,C])

covMatrix = np.cov(data.T,bias=True)
print (covMatrix)

[[228.66666667 140.         137.66666667  81.66666667 175.        ]
 [140.          86.22222222  87.77777778  51.33333333 107.33333333]
 [137.66666667  87.77777778 106.88888889  58.33333333 106.66666667]
 [ 81.66666667  51.33333333  58.33333333  32.66666667  63.        ]
 [175.         107.33333333 106.66666667  63.         134.        ]]
