LETTURA DI TUTTI I NOMI DI IMMAGINI NELLA CARTELLA ./olivetti_PNG_master/images/

In [39]:
# import OS module
import os

# Get the list of all files and directories
path = "./olivetti_PNG_master/images/"
dir_list = os.listdir(path)
 
print("Files and directories in '", path, "' :")
 
# prints all files
print(dir_list)

Files and directories in ' ./olivetti_PNG_master/images/ ' :
['image-243.png', 'image-257.png', 'image-280.png', 'image-294.png', 'image-52.png', 'image-46.png', 'image-91.png', 'image-85.png', 'image-109.png', 'image-135.png', 'image-121.png', 'image-337.png', 'image-323.png', 'image-9.png', 'image-8.png', 'image-322.png', 'image-336.png', 'image-120.png', 'image-134.png', 'image-108.png', 'image-84.png', 'image-90.png', 'image-47.png', 'image-53.png', 'image-295.png', 'image-281.png', 'image-256.png', 'image-242.png', 'image-268.png', 'image-254.png', 'image-240.png', 'image-297.png', 'image-283.png', 'image-45.png', 'image-51.png', 'image-79.png', 'image-86.png', 'image-92.png', 'image-122.png', 'image-136.png', 'image-308.png', 'image-320.png', 'image-334.png', 'image-335.png', 'image-321.png', 'image-309.png', 'image-137.png', 'image-123.png', 'image-93.png', 'image-87.png', 'image-78.png', 'image-50.png', 'image-44.png', 'image-282.png', 'image-296.png', 'image-241.png', 'image-2

In [61]:
from PIL import Image
from numpy import asarray
import numpy as np

# load and display an image with Matplotlib
from matplotlib import image
from matplotlib import pyplot

# load the image
image = Image.open('./olivetti_PNG_master/images/image-0.png')
# convert image to numpy array
data = asarray(image)

print("STAMPO IL NUMPY ARRAY")
print(data)

print("STAMPO IL TIPO DI NUMPY ARRAY")
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(" ", image2.mode)
print(image2.size)


# display the array of pixels as an image
# il parametro cmap serve a specificare il tipo di colormap che vogliamo utilizzare, per questo motivo abbiamo specificato gray per la scala di grigi
# pyplot.imshow(image, cmap='gray')
# pyplot.show()

im = np.array(image.convert('L')) #you can pass multiple arguments in single line
print("SONO QUA 1")

print(type(im))

# gr_im= Image.fromarray(im).save('gr_kolala.png')

print("SONO QUA 2")

grey_levels = 256

# Define the window size
windowsize_r = 8
windowsize_c = 8

arrayOf64LittleImages = []  # questo array contiene tutte le matrici corrispondenti ai vari tasselli dell'immagine grande

# Crop out the window and calculate the histogram
for r in range(0,data.shape[0] - windowsize_r, windowsize_r):
    for c in range(0,data.shape[1] - windowsize_c, windowsize_c):
        window = data[r:r+windowsize_r,c:c+windowsize_c]
        hist = np.histogram(window,bins=grey_levels)
        print(window)
        imagetest = Image.fromarray(window)
        print(window.mean(axis=0))
        arrayOf64LittleImages.append(window)
        # pyplot.imshow(imagetest, cmap='gray')
        # pyplot.show()

arrayOf64LittleImages




STAMPO IL NUMPY ARRAY
[[ 73  92 108 ...  93  80  72]
 [ 84 104 114 ...  93  82  74]
 [ 84 108 118 ...  96  82  69]
 ...
 [ 42  40  45 ...  23  27  29]
 [ 39  41  41 ...  21  25  27]
 [ 39  40  39 ...  23  25  24]]
STAMPO IL TIPO DI NUMPY ARRAY
<class 'numpy.ndarray'>
(64, 64)
<class 'PIL.Image.Image'>
  L
(64, 64)
SONO QUA 1
<class 'numpy.ndarray'>
SONO QUA 2
[[ 73  92 108 116 143 169 185 191]
 [ 84 104 114 125 151 174 189 194]
 [ 84 108 118 138 158 181 191 195]
 [ 72 105 125 142 165 183 190 191]
 [ 81 109 126 161 179 187 187 190]
 [ 74 100 126 170 183 183 187 186]
 [ 73  94 145 183 185 181 183 181]
 [ 58  90 153 183 181 177 178 181]]
[ 74.875 100.25  126.875 152.25  168.125 179.375 186.25  188.625]
[[195 194 199 198 197 198 195 197]
 [195 194 197 195 198 199 198 197]
 [197 197 198 195 199 201 201 199]
 [194 194 197 195 201 202 202 201]
 [193 191 193 195 199 201 202 202]
 [190 186 190 193 197 199 201 202]
 [186 187 194 194 197 197 201 202]
 [186 191 186 186 193 195 199 203]]
[192.    1

[array([[ 73,  92, 108, 116, 143, 169, 185, 191],
        [ 84, 104, 114, 125, 151, 174, 189, 194],
        [ 84, 108, 118, 138, 158, 181, 191, 195],
        [ 72, 105, 125, 142, 165, 183, 190, 191],
        [ 81, 109, 126, 161, 179, 187, 187, 190],
        [ 74, 100, 126, 170, 183, 183, 187, 186],
        [ 73,  94, 145, 183, 185, 181, 183, 181],
        [ 58,  90, 153, 183, 181, 177, 178, 181]], dtype=uint8),
 array([[195, 194, 199, 198, 197, 198, 195, 197],
        [195, 194, 197, 195, 198, 199, 198, 197],
        [197, 197, 198, 195, 199, 201, 201, 199],
        [194, 194, 197, 195, 201, 202, 202, 201],
        [193, 191, 193, 195, 199, 201, 202, 202],
        [190, 186, 190, 193, 197, 199, 201, 202],
        [186, 187, 194, 194, 197, 197, 201, 202],
        [186, 191, 186, 186, 193, 195, 199, 203]], dtype=uint8),
 array([[195, 198, 199, 199, 198, 201, 202, 205],
        [201, 202, 202, 203, 202, 199, 205, 207],
        [201, 202, 202, 203, 205, 203, 207, 210],
        [202, 201, 2

In [67]:
arrayOfMeans = [] # array che contiene la media di ogni tassello
arrayOfStd = [] # array che contiene la media di ogni tassello
arrayOfSkewness = [] # array che contiene la media di ogni tassello

# TODO: riguardare bene la skewness

for i in range(0, len(arrayOf64LittleImages)):
    #print(arrayOf64LittleImages[i].mean())
    arrayOfMeans.append(arrayOf64LittleImages[i].mean())
    arrayOfStd.append(arrayOf64LittleImages[i].std())
    arrayOfSkewness.append(skew(arrayOf64LittleImages[i]))

print(arrayOfMeans)
print(arrayOfStd)
# print(arrayOfSkewness)

numpyArrayOfMeans = np.array(arrayOfMeans)
print("Total mean of image: ", numpyArrayOfMeans.mean())



[147.078125, 196.09375, 203.921875, 223.53125, 214.203125, 203.359375, 202.6875, 148.6875, 179.3125, 166.984375, 208.671875, 202.453125, 157.171875, 175.390625, 183.5625, 174.703125, 148.109375, 185.375, 185.515625, 154.15625, 155.46875, 192.109375, 198.28125, 195.765625, 191.921875, 199.015625, 182.625, 190.484375, 186.15625, 218.015625, 205.125, 196.890625, 190.4375, 201.078125, 207.921875, 125.484375, 230.328125, 209.84375, 187.390625, 184.75, 209.953125, 212.78125, 63.296875, 227.015625, 197.640625, 160.28125, 148.78125, 190.390625, 195.421875]
[41.50425606470227, 4.512893854003216, 3.6967244263503063, 6.454089667606114, 8.637092406265838, 4.388789651985499, 5.237708826385827, 41.92175561388144, 21.999911221411782, 29.592805390151423, 8.538615753409625, 8.576730305563713, 27.063325442088136, 27.140040293068378, 27.788191624321293, 38.909221146591655, 26.566024582337775, 17.85488378567612, 25.43373263717646, 20.344854040702774, 36.91754695856024, 15.041730688633374, 5.87491688770998

In [41]:
#Calcolo della media dei vari tasselli

In [42]:
im.mean(axis=0)  #mean

# https://stackoverflow.com/questions/35586206/how-to-get-an-average-pixel-value-of-a-gray-scale-image-in-python-using-pil-nump

im.mean(axis=0).mean()

# la prima computazione della media calcola la media di ogni colonna della matrice e restituisce un numpy array
# la seconda computazione calcola la media del numpy array ottenuto restituendo un unico valore

178.140625

In [43]:
im.std(axis=0)   #standard deviation

im.std(axis=0).std()

15.788517473278398

In [44]:
from scipy.stats import skew

skew(skew(im))

1.0556716497463299

In [45]:
array = np.array([73, 84, 84, 72, 81, 74, 73, 58])

array.mean(axis = 0)

74.875