LETTURA DI TUTTI I NOMI DI IMMAGINI NELLA CARTELLA ./olivetti_PNG_master/images/

In [1]:
from PIL import Image
from numpy import asarray
import numpy as np

# load and display an image with Matplotlib
from matplotlib import image
from matplotlib import pyplot

# load the image
image = Image.open('./olivetti_PNG_master/images/image-0.png')
# convert image to numpy array
data = asarray(image)

print("STAMPO IL NUMPY ARRAY")
print(data)

print("STAMPO IL TIPO DI NUMPY ARRAY")
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(" ", image2.mode)
print(image2.size)


# display the array of pixels as an image
# il parametro cmap serve a specificare il tipo di colormap che vogliamo utilizzare, per questo motivo abbiamo specificato gray per la scala di grigi
# pyplot.imshow(image, cmap='gray')
# pyplot.show()

im = np.array(image.convert('L')) #you can pass multiple arguments in single line
print("SONO QUA 1")

print(type(im))

# gr_im= Image.fromarray(im).save('gr_kolala.png')

print("SONO QUA 2")

grey_levels = 256

# Define the window size
windowsize_r = 8
windowsize_c = 8

arrayOf64LittleImages = []  # questo array contiene tutte le matrici corrispondenti ai vari tasselli dell'immagine grande

# Crop out the window and calculate the histogram
for r in range(0,data.shape[0] - windowsize_r, windowsize_r):
    for c in range(0,data.shape[1] - windowsize_c, windowsize_c):
        window = data[r:r+windowsize_r,c:c+windowsize_c]
        hist = np.histogram(window,bins=grey_levels)
        print(window)
        imagetest = Image.fromarray(window)
        print(window.mean(axis=0))
        arrayOf64LittleImages.append(window)
        # pyplot.imshow(imagetest, cmap='gray')
        # pyplot.show()

arrayOf64LittleImages




STAMPO IL NUMPY ARRAY
[[ 73  92 108 ...  93  80  72]
 [ 84 104 114 ...  93  82  74]
 [ 84 108 118 ...  96  82  69]
 ...
 [ 42  40  45 ...  23  27  29]
 [ 39  41  41 ...  21  25  27]
 [ 39  40  39 ...  23  25  24]]
STAMPO IL TIPO DI NUMPY ARRAY
<class 'numpy.ndarray'>
(64, 64)
<class 'PIL.Image.Image'>
  L
(64, 64)
SONO QUA 1
<class 'numpy.ndarray'>
SONO QUA 2
[[ 73  92 108 116 143 169 185 191]
 [ 84 104 114 125 151 174 189 194]
 [ 84 108 118 138 158 181 191 195]
 [ 72 105 125 142 165 183 190 191]
 [ 81 109 126 161 179 187 187 190]
 [ 74 100 126 170 183 183 187 186]
 [ 73  94 145 183 185 181 183 181]
 [ 58  90 153 183 181 177 178 181]]
[ 74.875 100.25  126.875 152.25  168.125 179.375 186.25  188.625]
[[195 194 199 198 197 198 195 197]
 [195 194 197 195 198 199 198 197]
 [197 197 198 195 199 201 201 199]
 [194 194 197 195 201 202 202 201]
 [193 191 193 195 199 201 202 202]
 [190 186 190 193 197 199 201 202]
 [186 187 194 194 197 197 201 202]
 [186 191 186 186 193 195 199 203]]
[192.    1

[array([[ 73,  92, 108, 116, 143, 169, 185, 191],
        [ 84, 104, 114, 125, 151, 174, 189, 194],
        [ 84, 108, 118, 138, 158, 181, 191, 195],
        [ 72, 105, 125, 142, 165, 183, 190, 191],
        [ 81, 109, 126, 161, 179, 187, 187, 190],
        [ 74, 100, 126, 170, 183, 183, 187, 186],
        [ 73,  94, 145, 183, 185, 181, 183, 181],
        [ 58,  90, 153, 183, 181, 177, 178, 181]], dtype=uint8),
 array([[195, 194, 199, 198, 197, 198, 195, 197],
        [195, 194, 197, 195, 198, 199, 198, 197],
        [197, 197, 198, 195, 199, 201, 201, 199],
        [194, 194, 197, 195, 201, 202, 202, 201],
        [193, 191, 193, 195, 199, 201, 202, 202],
        [190, 186, 190, 193, 197, 199, 201, 202],
        [186, 187, 194, 194, 197, 197, 201, 202],
        [186, 191, 186, 186, 193, 195, 199, 203]], dtype=uint8),
 array([[195, 198, 199, 199, 198, 201, 202, 205],
        [201, 202, 202, 203, 202, 199, 205, 207],
        [201, 202, 202, 203, 205, 203, 207, 210],
        [202, 201, 2

In [2]:
from scipy.stats import skew

arrayOfMeans = [] # array che contiene la media di ogni tassello
arrayOfStd = [] # array che contiene la media di ogni tassello
arrayOfSkewness = [] # array che contiene la media di ogni tassello

# TODO: riguardare bene la skewness

for i in range(0, len(arrayOf64LittleImages)):
    #print(arrayOf64LittleImages[i].mean())
    arrayOfMeans.append(arrayOf64LittleImages[i].mean())
    arrayOfStd.append(arrayOf64LittleImages[i].std())
    arrayOfSkewness.append(skew(arrayOf64LittleImages[i]))

print(arrayOfMeans)
print(arrayOfStd)
# print(arrayOfSkewness)

numpyArrayOfMeans = np.array(arrayOfMeans)
print("Total mean of image: ", numpyArrayOfMeans.mean())



[147.078125, 196.09375, 203.921875, 223.53125, 214.203125, 203.359375, 202.6875, 148.6875, 179.3125, 166.984375, 208.671875, 202.453125, 157.171875, 175.390625, 183.5625, 174.703125, 148.109375, 185.375, 185.515625, 154.15625, 155.46875, 192.109375, 198.28125, 195.765625, 191.921875, 199.015625, 182.625, 190.484375, 186.15625, 218.015625, 205.125, 196.890625, 190.4375, 201.078125, 207.921875, 125.484375, 230.328125, 209.84375, 187.390625, 184.75, 209.953125, 212.78125, 63.296875, 227.015625, 197.640625, 160.28125, 148.78125, 190.390625, 195.421875]
[41.50425606470227, 4.512893854003216, 3.6967244263503063, 6.454089667606114, 8.637092406265838, 4.388789651985499, 5.237708826385827, 41.92175561388144, 21.999911221411782, 29.592805390151423, 8.538615753409625, 8.576730305563713, 27.063325442088136, 27.140040293068378, 27.788191624321293, 38.909221146591655, 26.566024582337775, 17.85488378567612, 25.43373263717646, 20.344854040702774, 36.91754695856024, 15.041730688633374, 5.87491688770998

In [3]:
#Calcolo della media dei vari tasselli

In [4]:
im.mean(axis=0)  #mean

# https://stackoverflow.com/questions/35586206/how-to-get-an-average-pixel-value-of-a-gray-scale-image-in-python-using-pil-nump

#im.mean(axis=0).mean()

# la prima computazione della media calcola la media di ogni colonna della matrice e restituisce un numpy array
# la seconda computazione calcola la media del numpy array ottenuto restituendo un unico valore

# test = np.matrix([[127 133 147 163 176 192 207 214],
#                     [124 137 150 166 185 201 216 217],
#                     [141 149 154 175 197 210 217 217],
#                     [152 153 169 188 210 211 214 216],
#                     [156 175 191 205 214 213 214 214],
#                     [173 195 207 213 216 213 213 210],
#                     [203 214 214 217 208 213 207 208],
#                     [213 214 213 213 211 208 207 205]])


array([ 86.90625 ,  94.140625, 116.921875, 135.046875, 148.09375 ,
       157.1875  , 165.4375  , 192.046875, 200.265625, 202.15625 ,
       202.9375  , 204.515625, 207.671875, 207.046875, 202.265625,
       196.375   , 194.484375, 192.421875, 191.703125, 192.796875,
       194.25    , 194.71875 , 195.1875  , 191.8125  , 190.34375 ,
       193.3125  , 193.09375 , 195.71875 , 196.515625, 195.0625  ,
       194.46875 , 196.703125, 199.15625 , 196.703125, 194.125   ,
       191.890625, 186.40625 , 183.65625 , 184.03125 , 180.765625,
       180.34375 , 183.296875, 186.328125, 187.765625, 189.90625 ,
       189.484375, 186.765625, 186.515625, 184.03125 , 188.9375  ,
       189.78125 , 192.40625 , 190.578125, 187.578125, 186.8125  ,
       185.609375, 183.640625, 181.765625, 170.03125 , 139.09375 ,
       122.421875, 105.421875,  88.703125,  75.4375  ])

In [5]:
im.std(axis=0)   #standard deviation

im.std(axis=0).std()

15.788517473278398

In [6]:
from scipy.stats import skew

skew(skew(im))

1.0556716497463299

In [7]:
array = np.array([73, 84, 84, 72, 81, 74, 73, 58])

array.mean(axis = 0)

74.875

In [8]:
# # https://www.programcreek.com/python/example/93593/skimage.feature.hog

# import matplotlib.pyplot as plt

# from skimage.feature import hog
# from skimage import data, exposure

# #TODO: capire come usare la nostra immagine grande

# # image = data.astronaut()


# # load the image
# image = Image.open('./olivetti_PNG_master/images/image-0.png')
# # convert image to numpy array
# data = asarray(image)
# print(data)

# fd, hog_image = hog(data, orientations=9, pixels_per_cell=(8, 8),
#                     cells_per_block=(2, 2), visualize=True, channel_axis=-1)

# fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

# ax1.axis('off')
# ax1.imshow(data, cmap=plt.cm.gray)
# ax1.set_title('Input image')

# # Rescale histogram for better display
# hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

# ax2.axis('off')
# ax2.imshow(hog_image_rescaled, cmap=plt.cm.gray)
# ax2.set_title('Histogram of Oriented Gradients')
# plt.show()

In [9]:
from scipy.stats import skew

def ottieniDescrittore(imageID, modelName):
    print("SONO QUA")
    # apriamo l'immagine
    image = Image.open('./olivetti_PNG_master/images/' + imageID)
    # convertiamo l'immagine in un numpy array
    data = asarray(image)
    print(data)

    arrayOf64LittleImages = getArrayOf64LittleImages(data)

    match modelName:
        case 'ColorMoments':
            return getColorMoments(arrayOf64LittleImages)
        case 'ELBP':
            return "Not found"
        case 'HOG':
            return "I'm a teapot"
        case _:
            return "Errore, inserire un descrittore corretto"

def getColorMoments(arrayOf64LittleImages):
        # print(arrayOf64LittleImages)

    arrayOfMeans = []  # array che contiene la media di ogni tassello
    arrayOfStd = []  # array che contiene la media di ogni tassello
    arrayOfSkewness = []  # array che contiene la media di ogni tassello
    
    # TODO: riguardare bene la skewness

    for i in range(0, len(arrayOf64LittleImages)):
        # print(arrayOf64LittleImages[i].mean())
        #print("Indice ", i)
        #print(arrayOf64LittleImages[i])
        # arrnp = np.asarray(arrayOf64LittleImages[i])
        # print("MEAN ", arrnp.mean())
        
        arrayOfMeans.append(arrayOf64LittleImages[i].mean())
        arrayOfStd.append(arrayOf64LittleImages[i].std())
        arrayOfSkewness.append(skew(skew(arrayOf64LittleImages[i])))    #TODO: ricontrollare bene come calcolare la skewness totale

    print("\nArray of means")
    print(arrayOfMeans)

    print("\nArray of Std")
    print(arrayOfStd)
    # print(arrayOfSkewness)

    print("\nArray of Skewness")
    print(arrayOfSkewness)

    numpyArrayOfMeans = np.array(arrayOfMeans)
    print("\nTotal mean of image: ", numpyArrayOfMeans.mean())

    numpyArrayOfStd = np.array(arrayOfStd)
    print("\nTotal std of image: ", numpyArrayOfStd.std())

    numpyArrayOfSkew = np.array(arrayOfSkewness)
    print("\nTotal skew of image: ", skew(numpyArrayOfSkew))
    

def getArrayOf64LittleImages(data):
    # TODO: riguardare questa cosa di grey scale
    grey_levels = 256

    # Define the window size
    windowsize_r = 8
    windowsize_c = 8

    # questo array contiene tutte le matrici corrispondenti ai vari tasselli dell'immagine grande
    arrayOf64LittleImages = []
    #arr = np.array((0, 3))

    # Crop out the window and calculate the histogram
    for r in range(0, data.shape[0] - windowsize_r, windowsize_r):
        for c in range(0, data.shape[1] - windowsize_c, windowsize_c):
            window = data[r:r+windowsize_r, c:c+windowsize_c]

            window_np = np.asarray(window)
            hist = np.histogram(window, bins=grey_levels)

            # print(window_np)
            imagetest = Image.fromarray(window)
            # print(window.mean(axis=0))
            arrayOf64LittleImages.append(window)
            #arr = np.append(arr, window)
            # print(arr)
            # pyplot.imshow(imagetest, cmap='gray')
            # pyplot.show()

    return arrayOf64LittleImages


In [10]:
ottieniDescrittore('image-1.png', 'ColorMoments')

SONO QUA
[[127 133 147 ...  34  32  32]
 [124 137 150 ...  42  41  41]
 [141 149 154 ...  38  39  39]
 ...
 [239 242 246 ...  17  17  17]
 [239 240 245 ...  15  15  15]
 [236 245 242 ...  20  20  20]]

Array of means
[192.46875, 213.15625, 225.765625, 234.21875, 217.8125, 210.40625, 197.703125, 209.328125, 191.890625, 160.328125, 186.125, 214.96875, 183.03125, 172.140625, 216.578125, 185.484375, 159.703125, 173.453125, 218.015625, 154.703125, 157.375, 222.0625, 212.59375, 209.390625, 206.21875, 209.4375, 193.34375, 186.671875, 235.4375, 229.21875, 208.75, 197.34375, 208.1875, 190.46875, 190.375, 236.296875, 237.984375, 208.890625, 183.96875, 167.46875, 192.4375, 141.96875, 218.0, 239.921875, 210.5, 195.828125, 173.203125, 179.984375, 65.640625]

Array of Std
[27.474970854170163, 4.880505705098602, 7.1539809448568565, 6.377373945245801, 3.427257467713799, 4.285581750182815, 10.872384293906052, 9.700281386865795, 30.471358061454612, 37.60072085724388, 28.901502988599052, 9.16339311813587