In [4]:

import numpy as np
from scipy.spatial import distance

arr0 = [0, 0, 0]
numpyArr0 = np.array(arr0)

arr1 = [9, 0, 0]
numpyArr1 = np.array(arr1)

arr2 = [3, 3, 3]
numpyArr2 = np.array(arr2)

dist01 = np.linalg.norm(numpyArr0 - numpyArr1)
dist02 = np.linalg.norm(numpyArr0 - numpyArr2)


print("dist01: ", dist01)
print("dist02: ", dist02)

dist01:  9.0
dist02:  5.196152422706632


In [5]:
covmat = np.cov(arr1)

In [12]:
np.linalg.inv(covmat)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [11]:
distance.mahalanobis(arr0, arr1, np.linalg.inv(covmat))

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [13]:
distance.hamming(arr0, arr1)

0.3333333333333333

In [14]:
distance.hamming(arr0, arr2)

1.0

In [16]:
distance.minkowski(arr0, arr1, 2)

9.0

In [17]:
distance.minkowski(arr0, arr2, 2)

5.196152422706632

In [19]:
distance.cityblock(arr0, arr1) # distanza di manhattan

9

In [19]:
array = [[127, 133],
 [203, 214],
 [213, 214]]


array


[[127, 133], [203, 214], [213, 214]]

In [20]:
arr = numpy.array(array)

arr

array([[127, 133],
       [203, 214],
       [213, 214]])

In [21]:
import numpy

vec = arr.reshape(-1)

In [22]:
vec

array([127, 133, 203, 214, 213, 214])

In [23]:
from scipy.stats import skew
skew(arr)

array([-0.67131388, -0.70710678])

In [25]:
skew(arr).mean()

-0.6892103282009432

In [24]:
skew(vec)

-0.68409396495599

In [29]:
array1 = [127, 203, 213]
array1 = numpy.array(array1)

skew(array1)

-0.6713138752153387