# Task 5
Scrivere un programma che , dato il nome del file contenente un’immagine query che potrebbe non essere presente nel database e un file di semantiche latenti, identifichi e visualizzi le n immagini piu’ simili rispetto alle semantiche latenti descritte nel file dato.


### Come pensiamo di fare?

Se usiamo un file con feature latenti formate da coppie tipo-peso quello che conviene fare è considerare il tipo dell'immagine di query e quindi:
- leggere l'intero file delle semantiche latenti e per ogni tipo creare un descrittore 
- dopodichè recuerare il descrittore corrispondente al tipo dell'immagine in input
- Calcolare una metrica (distanza o similarità) tra tutti i descrittori
- prendere i più simili a quello corrispondente alla query
- restituire le immagini le immagini dei tipi più simili

> **PROBLEMA**: di quei tipi abbiamo tante immagini di soggetti diversi, quali ovremmo prendere?

Faremmo un ragionamento analogo anche per il caso in cui si utilizza un file soggetto-peso

In [2]:
from ipynb.fs.full.functions_secondaparte import *
import numpy as np

In [3]:
directory = './outputfilesecondaparte/latent/'
getNsimilarImages('./secondaparte/images/image-cc-1-2.png', directory + 'LATENT_task1_ColorMoments_SVD.txt')

./secondaparte/images/image-cc-1-2.png
1
Sono in split
r:  64 , h: 64
prima del return
2
Numero di sottoimmagini:  64
Lunghezza array delle medie:  64
indice i  0
[[255 255 255 255 255 255 247 243]
 [255 255 255 255 255 232 212 224]
 [255 255 255 255 222 208 213 228]
 [255 255 255 246 198 219 239 246]
 [255 255 236 205 196 229 245 252]
 [255 234 193 197 217 237 249 255]
 [234 189 192 219 249 252 255 255]
 [204 217 226 230 249 255 255 255]]
[-1.72509247 -1.21000541 -0.71323204 -0.39758952 -0.30642995 -0.25158128
 -0.86368543 -0.79505437]
-0.9235178901167613
indice i  1
[[251 255 255 255 255 254 253 245]
 [232 242 253 255 255 255 255 255]
 [236 238 239 243 236 247 255 255]
 [255 248 244 250 244 250 251 243]
 [255 254 255 255 255 255 254 247]
 [249 255 255 255 255 255 244 233]
 [250 255 255 249 233 249 243 228]
 [255 255 250 209 199 255 255 240]]
[-0.96856548 -0.92093523 -1.07804064 -1.95724078 -1.40822132 -0.67876858
 -0.93844364 -0.23592253]
-2.4514997634058
indice i  2
[[242 255 255 25