# Task 2
Implementate un programma che, data una cartella di immagini, estragga e memorizzi i descrittori delle features illustrate al Task 1 per tutte le immagini nel folder.

In [19]:
from ipynb.fs.full.task1_new import ottieniDescrittore
import numpy as np
from operator import itemgetter

from PIL import Image
from numpy import asarray
from scipy.stats import skew

# load and display an image with Matplotlib
from matplotlib import image
from matplotlib import pyplot
import matplotlib.pyplot as plt

### Lettura di tutti i nomi dei file all'interno della cartella delle immagini
- la lista risultante conterrà tante stringhe quanti sono i file nella cartella ed ogni elemento della lista corrisponderà al nome dell'immagine in questione

In [20]:
# import OS module
import os

# Get the list of all files and directories
path = "./olivetti_PNG_master/images/"
dir_list = os.listdir(path) # array di stringhe contenente i nomi dei file
 
dir_list.sort()
dir_list.remove('.DS_Store')

### Salvataggio dei descrittori dei color moments

In [21]:
# salvataggio dei descrittori dei color moments

dictionaryOfColorMomentsDescriptors = {}

for i in range(0, len(dir_list)):
    colorMomentsOfImage = ottieniDescrittore(dir_list[i], 'ColorMoments')
    dictionaryOfColorMomentsDescriptors[dir_list[i]] = colorMomentsOfImage

### Salvataggio dei descrittori delle HOG features

In [22]:
# salvataggio dei descrittori delle HOG features

dictionaryOfHOGDescriptors = {}

for i in range(0, len(dir_list)):
    HOGofImage = ottieniDescrittore(dir_list[i], 'HOG')
    dictionaryOfHOGDescriptors[dir_list[i]] = HOGofImage

[0.54746698 0.         0.         ... 0.00242788 0.01360166 0.15256751]
[0.48765299 0.48765299 0.         ... 0.08296451 0.01249152 0.03335891]
[0.38619539 0.19142615 0.01739332 ... 0.         0.00879545 0.44692699]
[0.50868362 0.05095005 0.         ... 0.         0.02111302 0.1112641 ]
[0.44612816 0.01565625 0.0039905  ... 0.00636284 0.         0.17705465]
[0.53034093 0.00551584 0.0031375  ... 0.02705097 0.         0.1218691 ]
[0.33552551 0.04466087 0.00277739 ... 0.         0.00263698 0.07612845]
[0.41252437 0.41252437 0.03329625 ... 0.01039862 0.02357552 0.2381767 ]
[0.4491679  0.0151218  0.00113448 ... 0.01261532 0.00795593 0.20697132]
[0.42333909 0.         0.         ... 0.00316426 0.01042477 0.10791101]
[0.3450686  0.03236656 0.         ... 0.00272823 0.00186862 0.04774013]
[0.19071832 0.14910788 0.0057042  ... 0.         0.         0.11261207]
[0.50732239 0.00888792 0.         ... 0.         0.01882364 0.25723451]
[0.33991866 0.08118787 0.03038516 ... 0.01362329 0.0041809  0.07

### Salvataggio dei descrittori delle features LBP

In [23]:
# salvataggio dei descrittori delle features LBP

dictionaryOfLBPDescriptors = {}

for i in range(0, len(dir_list)):
    LBPofImage = ottieniDescrittore(dir_list[i], 'LBP')
    dictionaryOfLBPDescriptors[dir_list[i]] = LBPofImage