# Task 5
Scrivere un programma che , dato il nome del file contenente un’immagine query che potrebbe non essere presente nel database e un file di semantiche latenti, identifichi e visualizzi le n immagini piu’ simili rispetto alle semantiche latenti descritte nel file dato.


### Come pensiamo di fare?

Se usiamo un file con feature latenti formate da coppie tipo-peso quello che conviene fare è considerare il tipo dell'immagine di query e quindi 

In [2]:
from ipynb.fs.full.functions_secondaparte import *
import numpy as np

In [3]:
directory = './outputfilesecondaparte/'
getNsimilarImages('image-cc-1-2.png', directory + 'HOG_PCA_coppie_soggetto-peso-task4.txt')

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 229 228 228]
 [255 255 255 ... 246 239 240]
 ...
 [255 253 232 ... 255 255 255]
 [255 255 239 ... 255 255 255]
 [255 246 252 ... 242 242 242]]
